# Generated by Django 4.1.7 on 2023-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='news',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'Новость'), ('post', 'Статья')], default='news', max_length=4),
        ),
    ]
